syntax = "proto3";

package auth.v1;

option go_package = "auth/gen/auth/v1;authv1";


message VerifyUserExistsResponse{
    bool exists=1;
}

message VerifyUserExistsRequest{
    string id=1;
    string email =2;
}

message AuthenticateUserRequest{
    string sessionID=1;
}

message MinimalUserStruct{
    string userId = 1;
    string email = 2;
}

message AuthenticateUserResponse{
    bool allow =1;
    MinimalUserStruct user=2;
}


service AuthService {
  rpc VerifyUserExists(VerifyUserExistsRequest) returns (VerifyUserExistsResponse);
  rpc AuthenticateUser(AuthenticateUserRequest) returns (AuthenticateUserResponse);
}
